name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: docker-compose build
      - name: Stop old containers
        run: docker-compose down
      - name: Start new containers
        run: docker-compose up -d
      - name: Show first container logs
        run: docker-compose logs
