name: Check formatting

on:
  push:
    branches: [main, prettier_test]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn global add prettier
      - name: Check formatting
        run: prettier --check ./src/*
